chain_config: ./configs/genesis.json
secrets_config: ""
data_dir: "./data/avail-node-1"
block_gas_target: "0x0"
grpc_addr: ":20000"
jsonrpc_addr: ":20002"
node_type: "sequencer"
telemetry:
    prometheus_addr: ""
network:
    no_discover: false
    libp2p_addr: :20001
    nat_addr: ""
    dns_addr: ""
    max_peers: 40
    max_outbound_peers: 32
    max_inbound_peers: 8
seal: true
tx_pool:
    price_limit: 0
    max_slots: 4096
    max_account_enqueued: 10000
log_level: INFO
restore_file: ""
block_time_s: 2
ibft_base_time_s: 10
headers:
    access_control_allow_origins:
        - '*'
log_to: ""
