name: Releaser
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
jobs:
  build_and_publish_linux_arm64:
    permissions: write-all
    name: Build and publish for linux arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger submodule update
        env:
          SSH_KEY_FOR_SUBMODULE: ${{secrets.AVAIL_SETTLEMENT_SECRET_KEY}}
        run: |
          mkdir $HOME/.ssh && echo "$SSH_KEY_FOR_SUBMODULE" > $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa && git submodule update --init --recursive
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build all go binaries
        run: make build-all GOOS=linux GOARCH=arm64
      - name: Add avail-settlement binary to zip archive
        run: zip -j avail-settlement-linux-arm64.zip avail-settlement

      - name: Build assm go binary
        run: make build-assm GOOS=linux GOARCH=amd64
      - name: Add assm binary to zip archive
        run: zip -j assm-linux-amd64.zip assm/assm

      - name: Publish release for tags
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          release_name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
